params:
  seed: 10

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  load_checkpoint: False

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [64, 64, 64]
      d2rl: False
      activation: relu
      initializer:
        name: default
        scale: 1.0

  config:
    env_name: drone_racing_paper_task
    env_config:
      num_envs: 1024
      headless: True
      use_warp: False

    name: drone_racing_paper
    reward_shaper:
      scale_value: 1.0

    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    ppo: True
    learning_rate: 1e-4
    lr_schedule: adaptive
    kl_threshold: 0.016
    save_best_after: 20
    score_to_win: 100000
    grad_norm: 1.0
    entropy_coef: 0.003
    truncate_grads: True
    e_clip: 0.2
    clip_value: False
    num_actors: 1024
    horizon_length: 32
    minibatch_size: 8192
    mini_epochs: 4
    critic_coef: 2
    normalize_input: True
    bounds_loss_coef: 0.0001
    max_epochs: 2000000
    normalize_value: True
    use_diagnostics: True
    value_bootstrap: True
    use_smooth_clamp: False

    player:
      render: False
      deterministic: True
      games_num: 100
